KOREAN_BOOK_ABBREVIATIONS = [
    "창", "출", "레", "민", "신",
    "수", "삿", "룻",
    "삼상", "삼하",
    "왕상", "왕하",
    "대상", "대하",
    "스", "느", "에",
    "욥", "시", "잠", "전", "아",
    "사", "렘", "애", "겔", "단",
    "호", "욜", "암", "옵", "욘", "미", "나", "합", "습", "학", "슥", "말",
    "마", "막", "눅", "요", "행", "롬",
    "고전", "고후",
    "갈", "엡", "빌", "골",
    "살전", "살후",
    "딤전", "딤후",
    "딛", "몬", "히", "약",
    "벧전", "벧후",
    "요일", "요이", "요삼",
    "유", "계"
]

BIBLE_BOOKS = [
    {"id": 1, "ko": "창세기", "en": "Genesis", "abbr": "Gen", "abbr_ko": "창"},
    {"id": 2, "ko": "출애굽기", "en": "Exodus", "abbr": "Exo", "abbr_ko": "출"},
    {"id": 3, "ko": "레위기", "en": "Leviticus", "abbr": "Lev", "abbr_ko": "레"},
    {"id": 4, "ko": "민수기", "en": "Numbers", "abbr": "Num", "abbr_ko": "민"},
    {"id": 5, "ko": "신명기", "en": "Deuteronomy", "abbr": "Deu", "abbr_ko": "신"},
    {"id": 6, "ko": "여호수아", "en": "Joshua", "abbr": "Jos", "abbr_ko": "수"},
    {"id": 7, "ko": "사사기", "en": "Judges", "abbr": "Jud", "abbr_ko": "삿"},
    {"id": 8, "ko": "룻기", "en": "Ruth", "abbr": "Rut", "abbr_ko": "룻"},
    {"id": 9, "ko": "사무엘상", "en": "1 Samuel", "abbr": "1Sa", "abbr_ko": "삼상"},
    {"id": 10, "ko": "사무엘하", "en": "2 Samuel", "abbr": "2Sa", "abbr_ko": "삼하"},
    {"id": 11, "ko": "열왕기상", "en": "1 Kings", "abbr": "1Ki", "abbr_ko": "왕상"},
    {"id": 12, "ko": "열왕기하", "en": "2 Kings", "abbr": "2Ki", "abbr_ko": "왕하"},
    {"id": 13, "ko": "역대상", "en": "1 Chronicles", "abbr": "1Ch", "abbr_ko": "대상"},
    {"id": 14, "ko": "역대하", "en": "2 Chronicles", "abbr": "2Ch", "abbr_ko": "대하"},
    {"id": 15, "ko": "에스라", "en": "Ezra", "abbr": "Ezr", "abbr_ko": "스"},
    {"id": 16, "ko": "느헤미야", "en": "Nehemiah", "abbr": "Neh", "abbr_ko": "느"},
    {"id": 17, "ko": "에스더", "en": "Esther", "abbr": "Est", "abbr_ko": "에"},
    {"id": 18, "ko": "욥기", "en": "Job", "abbr": "Job", "abbr_ko": "욥"},
    {"id": 19, "ko": "시편", "en": "Psalms", "abbr": "Psa", "abbr_ko": "시"},
    {"id": 20, "ko": "잠언", "en": "Proverbs", "abbr": "Pro", "abbr_ko": "잠"},
    {"id": 21, "ko": "전도서", "en": "Ecclesiastes", "abbr": "Ecc", "abbr_ko": "전"},
    {"id": 22, "ko": "아가", "en": "Song of Solomon", "abbr": "Sng", "abbr_ko": "아"},
    {"id": 23, "ko": "이사야", "en": "Isaiah", "abbr": "Isa", "abbr_ko": "사"},
    {"id": 24, "ko": "예레미야", "en": "Jeremiah", "abbr": "Jer", "abbr_ko": "렘"},
    {"id": 25, "ko": "예레미야애가", "en": "Lamentations", "abbr": "Lam", "abbr_ko": "애"},
    {"id": 26, "ko": "에스겔", "en": "Ezekiel", "abbr": "Ezk", "abbr_ko": "겔"},
    {"id": 27, "ko": "다니엘", "en": "Daniel", "abbr": "Dan", "abbr_ko": "단"},
    {"id": 28, "ko": "호세아", "en": "Hosea", "abbr": "Hos", "abbr_ko": "호"},
    {"id": 29, "ko": "요엘", "en": "Joel", "abbr": "Jol", "abbr_ko": "욜"},
    {"id": 30, "ko": "아모스", "en": "Amos", "abbr": "Amo", "abbr_ko": "암"},
    {"id": 31, "ko": "오바댜", "en": "Obadiah", "abbr": "Obd", "abbr_ko": "옵"},
    {"id": 32, "ko": "요나", "en": "Jonah", "abbr": "Jon", "abbr_ko": "욘"},
    {"id": 33, "ko": "미가", "en": "Micah", "abbr": "Mic", "abbr_ko": "미"},
    {"id": 34, "ko": "나훔", "en": "Nahum", "abbr": "Nah", "abbr_ko": "나"},
    {"id": 35, "ko": "하박국", "en": "Habakkuk", "abbr": "Hab", "abbr_ko": "합"},
    {"id": 36, "ko": "스바냐", "en": "Zephaniah", "abbr": "Zep", "abbr_ko": "습"},
    {"id": 37, "ko": "학개", "en": "Haggai", "abbr": "Hag", "abbr_ko": "학"},
    {"id": 38, "ko": "스가랴", "en": "Zechariah", "abbr": "Zec", "abbr_ko": "슥"},
    {"id": 39, "ko": "말라기", "en": "Malachi", "abbr": "Mal", "abbr_ko": "말"},
    {"id": 40, "ko": "마태복음", "en": "Matthew", "abbr": "Mat", "abbr_ko": "마"},
    {"id": 41, "ko": "마가복음", "en": "Mark", "abbr": "Mrk", "abbr_ko": "막"},
    {"id": 42, "ko": "누가복음", "en": "Luke", "abbr": "Luk", "abbr_ko": "눅"},
    {"id": 43, "ko": "요한복음", "en": "John", "abbr": "Jhn", "abbr_ko": "요"},
    {"id": 44, "ko": "사도행전", "en": "Acts", "abbr": "Act", "abbr_ko": "행"},
    {"id": 45, "ko": "로마서", "en": "Romans", "abbr": "Rom", "abbr_ko": "롬"},
    {"id": 46, "ko": "고린도전서", "en": "1 Corinthians", "abbr": "1Co", "abbr_ko": "고전"},
    {"id": 47, "ko": "고린도후서", "en": "2 Corinthians", "abbr": "2Co", "abbr_ko": "고후"},
    {"id": 48, "ko": "갈라디아서", "en": "Galatians", "abbr": "Gal", "abbr_ko": "갈"},
    {"id": 49, "ko": "에베소서", "en": "Ephesians", "abbr": "Eph", "abbr_ko": "엡"},
    {"id": 50, "ko": "빌립보서", "en": "Philippians", "abbr": "Php", "abbr_ko": "빌"},
    {"id": 51, "ko": "골로새서", "en": "Colossians", "abbr": "Col", "abbr_ko": "골"},
    {"id": 52, "ko": "데살로니가전서", "en": "1 Thessalonians", "abbr": "1Th", "abbr_ko": "살전"},
    {"id": 53, "ko": "데살로니가후서", "en": "2 Thessalonians", "abbr": "2Th", "abbr_ko": "살후"},
    {"id": 54, "ko": "디모데전서", "en": "1 Timothy", "abbr": "1Ti", "abbr_ko": "딤전"},
    {"id": 55, "ko": "디모데후서", "en": "2 Timothy", "abbr": "2Ti", "abbr_ko": "딤후"},
    {"id": 56, "ko": "디도서", "en": "Titus", "abbr": "Tit", "abbr_ko": "딛"},
    {"id": 57, "ko": "빌레몬서", "en": "Philemon", "abbr": "Phm", "abbr_ko": "몬"},
    {"id": 58, "ko": "히브리서", "en": "Hebrews", "abbr": "Heb", "abbr_ko": "히"},
    {"id": 59, "ko": "야고보서", "en": "James", "abbr": "Jas", "abbr_ko": "약"},
    {"id": 60, "ko": "베드로전서", "en": "1 Peter", "abbr": "1Pe", "abbr_ko": "벧전"},
    {"id": 61, "ko": "베드로후서", "en": "2 Peter", "abbr": "2Pe", "abbr_ko": "벧후"},
    {"id": 62, "ko": "요한일서", "en": "1 John", "abbr": "1Jn", "abbr_ko": "요일"},
    {"id": 63, "ko": "요한이서", "en": "2 John", "abbr": "2Jn", "abbr_ko": "요이"},
    {"id": 64, "ko": "요한삼서", "en": "3 John", "abbr": "3Jn", "abbr_ko": "요삼"},
    {"id": 65, "ko": "유다서", "en": "Jude", "abbr": "Jud", "abbr_ko": "유"},
    {"id": 66, "ko": "요한계시록", "en": "Revelation", "abbr": "Rev", "abbr_ko": "계"}
]

# Quick mapping dictionary for book names to IDs
BOOK_KO_TO_ID = {b["ko"]: b["id"] for b in BIBLE_BOOKS}
